### ISSUE TITLE
Application not reading sereno.yml configuration

### ISSUE THREAD

**Issue by marktopper** [serenohq/sereno#7]
It seems that the application is not reading from `sereno.yml` configuration.

I have changed the `siteName`, however after I build the site it still says `My Serene Website`.

**Comment by marktopper** [comment]
I figured out that it is reading the `config.php` file and not the predefined `sereno.yml` file. 👍

**Comment by znck** [comment]
^ You have to update composer dependencies. 

See https://github.com/serenohq/sereno/blob/master/composer.json#L13-L15

**Comment by marktopper** [comment]
Ahh, thanks for clearing that out @znck.

Maybe that should be changed in the default application files that are used when creating a new Sereno application.

**Comment by znck** [comment]
Lately caught up with stuff. I'll try to cleanup the project this weekend.
